DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE (
        id NUMBER(10) NOT NULL,
        firstName VARCHAR2(50) NOT NULL,
        lastName VARCHAR2(50) NOT NULL,
        PRIMARY KEY(id)
        );
